### ISSUE TITLE
Visual Studio 64 bit builds produce /arch:SSE2 warnings

### ISSUE THREAD

**Issue by reganheath** [weidai11/cryptopp#445]
1>cl : Command line warning D9002: ignoring unknown option '/arch:SSE2'

This is triggered by the:
      <EnableEnhancedInstructionSet>StreamingSIMDExtensions2</EnableEnhancedInstructionSet>
project setting in the group..
  <ItemDefinitionGroup Condition="'$(Platform)'=='x64'" Label="X64 Configuration">

This causes the /arch:SSE2 compile option which is only supported on x86 (32 bit).

The help text for this option says "If no option is specified, the compiler will use instructions found on processors that support SSE2." so perhaps no option should be set in either configuration..

**Comment by MarcelRaad** [comment]
Unfortunately it's still required for older Visual Studio versions. I think SSE2 was made the default in Visual Studio 2012.
But the property can and should be removed from the x64 block as SSE2 is always enabled for x64 and the only thing it does is generate this warning.

**Comment by MarcelRaad** [comment]
@reganheath Should be fixed with https://github.com/weidai11/cryptopp/commit/3485d2180d9bdf2edadbfbb3deee2263083461b5, can you confirm?

**Comment by reganheath** [comment]
Unfortunately I cannot.  We build an older version of the project for stability reasons.  I can say that the change I made to our copy matches the change shown in the diff (excluding the blank lines fixes #446).

**Comment by noloader** [comment]
Also see [Command line warning D9002: ignoring unknown option '/arch:SSE2'](https://connect.microsoft.com/VisualStudio/feedback/details/1217151) on Microsoft Connect. Its an active bug, but I believe it was fixed in VS2017. I don't recall seeing it during brief testing under VS2017.

**Comment by noloader** [comment]
Can this issue be closed?

**Comment by reganheath** [comment]
Yep

-----Original Message-----

**Comment by noloader** [comment]
Ack, thanks.

**Comment by sebas77** [comment]
hmm this is still happening to me with the latest vs17 but at least I know I don't need to enable the option

**Comment by NiallHornFX** [comment]
Was this fixed in 15.3.4? Still getting this.

**Comment by mgradwohl** [comment]
Please document /d2archSSE42

**Comment by heartbitt** [comment]
Still showing on 2022
